# Generated by Django 6.1 on 2026-08-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="papers/")),
                ("title", models.CharField(blank=True, max_length=500)),
                ("authors", models.CharField(blank=True, max_length=500)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("order_position", models.IntegerField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("raw_ai_data", models.JSONField(blank=True, default=dict)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="research.research",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="research.research",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cited_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations_received",
                        to="research.paper",
                    ),
                ),
                (
                    "citing_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations_made",
                        to="research.paper",
                    ),
                ),
            ],
            options={
                "unique_together": {("citing_paper", "cited_paper")},
            },
        ),
        migrations.CreateModel(
            name="PaperConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("introduces", "Introduces"),
                            ("requires", "Requires"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_concepts",
                        to="research.concept",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_concepts",
                        to="research.paper",
                    ),
                ),
            ],
            options={
                "unique_together": {("paper", "concept", "role")},
            },
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="research.paper",
                    ),
                ),
                (
                    "prerequisite_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by",
                        to="research.paper",
                    ),
                ),
            ],
            options={
                "unique_together": {("paper", "prerequisite_paper")},
            },
        ),
    ]
